build: old workflows

diff --git a/.github/workflows/pull-request.yml b/.github/workflows/pull-request.yml
--- a/.github/workflows/pull-request.yml
+++ b/.github/workflows/pull-request.yml
@@ -5,9 +5,6 @@ on:
     branches:
       - master
 
-env:
-  TODO_COUNT_BADGE_PATH: .github/assets/todo-count-badge.svg
-
 jobs:
   independent:
     runs-on: ubuntu-latest
@@ -51,7 +48,7 @@ jobs:
       - name: run mypy
         run: uv run mypy --config pyproject.toml .
       - name: run ruff
-        run: uv run ruff check wunderkafka tests
+        run: uv run ruff check .
 
   checks:
     needs: [independent]
@@ -112,60 +109,38 @@ jobs:
         uses: actions/checkout@v4
         with:
           fetch-depth: '0'
-      - name: Switch branch
-        run: git checkout $GITHUB_HEAD_REF
-
-      - name: Python Semantic Release
-        uses: python-semantic-release/python-semantic-release@v9.19.1
-        with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-  todo_counter:
-    runs-on: ubuntu-latest
-    name: Generate todo-counter Badge
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-        with:
-          ref: ${{ github.head_ref }}
-      - name: Count Todo
-        id: count_todo
-        run: echo "todo-num=$(grep -riw "todo" wunderkafka tests | wc -l | xargs)" >> $GITHUB_OUTPUT
-      - name: Generate the badge SVG image
-        uses: emibcn/badge-action@v1
-        with:
-          label: 'TODOs'
-          status: ${{ steps.count_todo.outputs.todo-num }}
-          path: ${{ env.TODO_COUNT_BADGE_PATH }}
-          color: ${{
-            steps.count_todo.outputs.todo-num < 5  && 'green'              ||
-            steps.count_todo.outputs.todo-num < 10 && 'yellow,green'       ||
-            steps.count_todo.outputs.todo-num < 15 && 'yellow'             ||
-            steps.count_todo.outputs.todo-num < 20 && 'orange,yellow'      ||
-            steps.count_todo.outputs.todo-num < 25 && 'orange'             ||
-            steps.count_todo.outputs.todo-num < 40 && 'red,orange'         ||
-            steps.count_todo.outputs.todo-num < 50 && 'red,red,orange'     ||
-            steps.count_todo.outputs.todo-num < 60 && 'red,red,red,orange' ||
-            'red' }}
-      - name: Verify Changed files
-        uses: tj-actions/verify-changed-files@v17
-        id: verify-changed-files
-        with:
-          files: ${{ env.TODO_COUNT_BADGE_PATH }}
-      - name: Commit badge
-        if: steps.verify-changed-files.outputs.files_changed == 'true'
+      - name: Get git tag.
+        id: get_tag
+        # ToDo (tribunsky.kir): replace it with semver autobumper
         run: |
-          git pull
-          git config --local user.email "action@github.com"
-          git config --local user.name "GitHub Action"
-          git add $TODO_COUNT_BADGE_PATH
-          git commit -m "chore: update todo-counter badge"
+          get_version () {
+            local VERSION=''
+            local LAST_GIT_TAG=''
+            LAST_GIT_TAG=$(git tag --merged origin/master | sort -V | tail -n 1)
+            VERSION=$(echo "${LAST_GIT_TAG}" | grep -P '^v\d+\.\d+.\d+$' | sed 's/^v//')
+            echo "$VERSION"
+          }
 
-      - name: Push badge commit
-        if: steps.verify-changed-files.outputs.files_changed == 'true'
-        uses: ad-m/github-push-action@master
-        with:
-          github_token: ${{ secrets.github_token }}
-          branch: ${{ github.head_ref }}
+          increment_version() {
+            local version=${1}
+            local section=${2}
+            local delimiter=.
+            local array=($(echo "$version" | tr $delimiter '\n'))
+            array[$section]=$((array[$section]+1))
+            echo $(local IFS=$delimiter ; echo "${array[*]}")
+          }
+          
+          VERSION_TAG="$(get_version)"
+          echo "Extracted latest tag from master branch: ${VERSION_TAG}"
+          if [ -z "${VERSION_TAG}" ]; then
+            echo "Couldn't detect any existing revision number. Please, place a tag."
+            exit 1
+          else
+            BUILD_VERSION="$(increment_version ${VERSION_TAG} 2).dev${GITHUB_RUN_NUMBER}"
+            echo "Got revision number for a current build: ${BUILD_VERSION}"
+            echo tag="${BUILD_VERSION}" >> $GITHUB_OUTPUT
+          fi
+
   deploy:
     needs: [checks, version]
     runs-on: ubuntu-latest
diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,14 +1,16 @@
 name: release
 
 on:
-  workflow_dispatch: null
-  release:
-    types:
-      - published
+  push:
+    branches:
+      - master
+    tags:
+      - v*
 
 jobs:
   version:
     runs-on: ubuntu-latest
+    if: ${{ github.ref_type == 'tag' && github.event.base_ref=='refs/heads/master' }}
     outputs:
       tag: ${{ steps.get_tag.outputs.tag }}
     steps:
@@ -16,13 +18,26 @@ jobs:
         uses: actions/checkout@v4
         with:
           fetch-depth: '0'
-      - name: Switch branch
-        run: git checkout ${{ github.ref_name }}
-
-      - name: Python Semantic Release
-        uses: python-semantic-release/python-semantic-release@v9.19.1
-        with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
+      - name: Get git tag.
+        id: get_tag
+        run: |
+          get_version () {
+            local VERSION=''
+            local LAST_GIT_TAG=''
+            LAST_GIT_TAG=$(git tag --merged origin/master | sort -V | tail -n 1)
+            VERSION=$(echo "${LAST_GIT_TAG}" | grep -P '^v\d+\.\d+.\d+$' | sed 's/^v//')
+            echo "$VERSION"
+          }
+          
+          VERSION_TAG="$(get_version)"
+          echo "Extracted latest tag from master branch: ${VERSION_TAG}"
+          if [ -z "${VERSION_TAG}" ]; then
+            echo "Couldn't detect any existing revision number. Please, place a tag."
+            exit 1
+          else
+            echo "Got revision number for a current build: ${VERSION_TAG}"
+            echo tag="${VERSION_TAG}" >> $GITHUB_OUTPUT
+          fi
 
   deploy:
     needs: [version]
